make: improve builds on old distros with pre-edition2024 Rust
libpathrs itself is buildable with pre-1.85 Rust but the existence of
test-only crates in our workspace that have transitive post-edition2024
dependencies causes builds of libpathrs to fail with older cargo
versions:

  error: failed to get `anyhow` as a dependency of package `fake-enosys v0.0.0 (/home/abuild/rpmbuild/BUILD/libpathrs-0.2.5/contrib/fake-enosys)`
  ...
  Caused by:
    failed to parse the `edition` key
  Caused by:
    this version of Cargo is older than the `2024` edition, and only supports `2015`, `2018`, and `2021` editions.

The hacky solution here is to extend hack/with-crate-type.sh to also
remove the workspace.members key from Cargo.toml when doing builds via
make. This works fine except that we now also need to make backups of
Cargo.lock because dropping workspace members causes cargo to GC the
dependencies locked in Cargo.lock -- which we don't want.

Unfortunately this means that with-crate-type.sh will probably need to
remain for longer than I hoped (originally it was meant to be dropped
with an MSRV of 1.64).

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>