mypy: re-add ignore for ffi.NULL check
This is a partial revert of 797b29eb696b48050773d5b4101759527ca0f1c6.

For some reason CI doesn't like this, but my local mypy really needs
this ignore line, otherwise you get annoying errors like:

  $ make -C ./contrib/bindings/python lint
  pathrs/_internal.py:96: error: Non-overlapping equality check (left operand type: "CError", right operand type: "CType")  [comparison-overlap]

Fixes: 797b29eb696b ("mypy: fix new errors")
Signed-off-by: Aleksa Sarai <aleksa@amutable.com>