gha: workaround for cargo-llvm-cov build-dir v2 regression
Rust nightly-2026-07-30 enabled the v2 build-dir layout for builds,
which /is/ supported by cargo-llvm-cov and cargo-nextest but
unfortunately the way they handle it is not incompatible. cargo-llvm-cov
relies on a special "fingerprint" directory being present to look for a
v2 build-dir layout but "cargo-nextest archive" does not include that
directory in the archive (instead the relevant information is stored in
a metadata JSON file that cargo-llvm-cov should probably be parsing
instead).

Until the issue is fixed in cargo-llvm-cov (or cargo-nextest adds a
workaround), work around the issue by creating the special "fingerprint"
directory after we extract the cargo-nextest archive ourselves.

Without this patch, the coverage-related CI jobs failed with the
following error as cargo-llvm-cov couldn't find the right directory for
the objects:

  error: failed to collect object files: not found object files
  (searched directories: .../target/llvm-cov-target/target/debug);
  this may occur if show-env subcommand is used incorrectly (see docs or other warnings), or unsupported commands or configs are used

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>