ci: make empty target/llvm-cov-target directory
CI has started erroring out with the error:

  + cargo llvm-cov --no-report --branch nextest --archive-file nextest-pathrs-unpriv.tar.zst ...
  error: error extracting archive `nextest-pathrs-unpriv.tar.zst`
  Caused by:
    error canonicalizing destination directory `/home/runner/work/libpathrs/libpathrs/target/llvm-cov-target`
  Caused by:
    No such file or directory (os error 2)

So make the missing directory.

Signed-off-by: Aleksa Sarai <aleksa@amutable.com>